### ISSUE TITLE
Is this attribute used?

### ISSUE THREAD

**Issue by camallen** [zooniverse/zoo-stats-api-graphql#39]
https://github.com/zooniverse/zoo-stats-api-graphql/blob/b1c8874cbc2b35b15b9d52ffd7a6c87928939734/db/schema.rb#L24

Just wondering what this attribute does and if it's used in queries / how it differs from `event_time` and the `created_at`, `updated_at` timestamps?

**Comment by AroneyS** [comment]
I don't think it is used. Should probably be removed. I think it is a leftover from the prototype sinatra api.
